Bugifx: fix AttributeError from missing attribute
When trying to create the commit message for the new batch of talks, the
download script throws an error:

```
File "./pyvideo_scrape.py", line 235, in create_commit
    '\n\nEvent config:\n~~~yaml\n{}\n~~~\n'.format(self.event_data_yaml)
AttributeError: 'Event' object has no attribute 'event_data_yaml'
```

This diff fixes the problem by making the data available without needing
it to be stored as an object attribute.